services:
  postgres:
    image: postgres
    container_name: directory_postgres
    restart: always
    environment:
      POSTGRES_DB: directory_project
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - postgres-directory-data:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    container_name: directory_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5342:5431
      - 8082:80
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-directory-data:/data
    command: server --console-address ":9001" /data
    restart: always
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

volumes:
  postgres-directory-data:
  minio-directory-data:
  rabbitmq_data:
