services:
  postgres:
    image: postgres
    container_name: directory_postgres
    restart: always
    environment:
      POSTGRES_DB: directory_project
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - postgres-directory-data:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    container_name: directory_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5342:5431
      - 8082:80

volumes:
  postgres-directory-data:
